<?php

/**
 * BookTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BookTable extends Doctrine_Table {
  /**
   * Returns an instance of this class.
   *
   * @return object BookTable
   */
  public static function getInstance() {
    return Doctrine_Core::getTable('Book');
  }

  public function getAll() {
    return $this->createQuery('b')
  		->select('b.id, b.title, b.is_read, b.rating, a.name AS author, c.name AS category')
  		->innerJoin('b.Author a')
  		->innerJoin('b.Category c')
      ->execute();
  }
}
